
# Zeke - Main Makefile
#
# Copyright (c) 2013 Olli Vanhoja <olli.vanhoja@cs.helsinki.fi>
# Copyright (c) 2012, 2013, Olli Vanhoja <olli.vanhoja@ninjaware.fi>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met: 
#
#1. Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer. 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution. 
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Configuration files ##########################################################
# Kernel config
CONFIG_MK  = ./config/config.mk
# Autogenerated header file
AUTOCONF_H = ./config/autoconf.h
################################################################################
include $(CONFIG_MK)
ifndef configMCU_MODEL
$(error Missing configMCU_MODEL!)
endif
ifndef configARCH
$(error Missing configARCH!)
endif

# Makefiles for modules ########################################################
# Atm for sake of simplicity we keep all makefiles on single level
MODMKFILES = $(wildcard *.mk)
include $(MODMKFILES)
# Following will generate a list of module names
MODULES = $(basename $(notdir $(MODMKFILES)))

# Generic Compiler Options #####################################################
ARMGNU   = arm-none-eabi
CCFLAGS  = -std=c99 -emit-llvm -Wall -ffreestanding -O2
CCFLAGS += -nostdlib -nostdinc
CCFLAGS += -m32 -ccc-host-triple $(ARMGNU)
OFLAGS   = -std-compile-opts
LLCFLAGS = -mtriple=$(ARMGNU)
ASFLAGS  =#
################################################################################

# Target Specific Compiler Options #############################################
# Arch specific flags
ifeq ($(configARCH),__ARM6M__)
	LLCFLAGS += -march=thumb
	ASFLAGS  += -mcpu=cortex-m0 -mthumb -EL
	# or more generic with
	#ASFLAGS  march=armv6-m -mthumb -EL
endif
ifeq ($(configARCH),__ARM6__)
	LLCFLAGS += -march=arm
	ASFLAGS  += -march=armv6 -EL
endif
# TODO Enable thumb?
ifeq ($(configARCH),__ARM6K__)
	LLCFLAGS += -march=arm
	ASFLAGS  += -march=armv6k -EL
endif

# MCU specific flags
ifeq ($(configMCU_MODEL),MCU_MODEL_STM32F0)
	CCFLAGS  += -DUSE_STDPERIPH_DRIVER -DSTM32F0XX
endif

# Floating point hardware
ifeq ($(configHFP),__HFP_VFP__)
	ASFLAGS  += -mfpu=vfp
endif
################################################################################
ifndef ASFLAGS
$(error Missing ASFLAGS! Wrong configARCH?)
endif

# Dirs #########################################################################
IDIR = ./include ./config ./src
################################################################################

# Select Modules ###############################################################
# Available selections:
SRC-	=# C sources
SRC-0  	=#
SRC-1  	=#
ASRC-  	=# Assembly sources
ASRC-0 	=#
ASRC-1	=#
# SRC- and SRC-0 meaning module will not be compiled

# Include sources from modules
SRC-1 += $(foreach var,$(MODULES), $($(var)-SRC-1))
ASRC-1 += $(foreach var,$(MODULES), $($(var)-ASRC-1))

################################################################################
# Assembly Obj files
ASOBJS 	:= $(patsubst %.S, %.o, $(ASRC-1))
# C Obj files
BCS  	:= $(patsubst %.c, %.bc, $(SRC-1))
OBJS 	:= $(patsubst %.c, %.o, $(SRC-1))

# Target specific Startup code & CRT ###########################################
# Memmap & vector table is set per MCU/CPU model
ifeq ($(configMCU_MODEL),MCU_MODEL_STM32F0)
	MEMMAP = config/memmap_stm32f051x8.ld
	STARTUP = src/hal/stm32f0/startup_stm32f0xx.S
endif
ifeq ($(configMCU_MODEL),MCU_MODEL_BCM2835)
	MEMMAP = config/memmap_bcm2835.ld
	STARTUP = src/hal/bcm2835/startup_bcm2835.S
endif
# Check that MEMMAP and STARTUP are defined
ifndef MEMMAP
$(error Missing MEMMAP! Wrong configMCU_MODEL?)
endif
ifndef STARTUP
$(error Missing STARTUP! Wrong configMCU_MODEL?)
endif

# CRT is compiled per instruction set or per core model
ifeq ($(configARM_PROFILE_M),1)
	# libgcc for ARMv6-M
	ifeq ($(configARCH),__ARM6M__)
		CRT = Libraries/crt/libaeabi-armv6-m/libaeabi-armv6-m.a
	endif
else
	ifeq ($(configARCH),__ARM6K__)
		CRT = Libraries/crt/libaeabi-armv6k/libaeabi-armv6k.a
	endif
endif
# Check that CRT is defined
ifndef CRT
	$(error Missing CRT! Wrong configMCU_MODEL or configARCH?)
endif
CRT_DIR = $(dir $(CRT))
################################################################################
IDIR := $(patsubst %,-I%,$(subst :, ,$(IDIR)))
STARTUP_O = $(patsubst %.S, %.o, $(STARTUP))

# A files for modules
MODAS = $(addsuffix .a, $(MODULES))

# We use suffixes because it's fun
.SUFFIXES:					# Delete the default suffixes
.SUFFIXES: .c .bc .o .h		# Define our suffix list

# Targets ######################################################################

# target: all - Make config and compile kernel
all: config kernel

# target: config - Update configuration from $(CONFIG_MK)
config: $(AUTOCONF_H)

# target: test - Run all portable unit tests
test:
	cd test/universal && make
	cd test/kstring && make

# target: clean-test - Clean portable test targets
clean-test:
	cd test/universal && make clean
	cd test/kstring && make clean

$(AUTOCONF_H): $(CONFIG_MK)
	./tools/aconf.sh $(CONFIG_MK) $(AUTOCONF_H)

$(CONFIG_MK):
# End of config

kernel: kernel.bin

$(STARTUP_O): $(STARTUP)
	$(ARMGNU)-as $< -o $(STARTUP_O)

$(ASOBJS): $(ASRC-1)
	$(ARMGNU)-as $*.S -o $@

$(BCS): $(SRC-1)
	clang $(CCFLAGS) $(IDIR) -c $*.c -o $@

$(OBJS): $(BCS)
	$(eval CUR_OPT := $*.opt.bc)
	$(eval CUR_OPT_S := $*.opt.s)
	opt-3.0 $(OFLAGS) $*.bc -o $(CUR_OPT)
	llc-3.0 $(LLCFLAGS) $(CUR_OPT) -o $(CUR_OPT_S)
	$(ARMGNU)-as $(CUR_OPT_S) -o $@ $(ASFLAGS)

$(CRT):
	make -C $(CRT_DIR) all

$(MODAS): $(ASOBJS) $(OBJS)
	@echo "Module: $@"
	$(eval CUR_MODULE := $(basename $@))
	$(eval CUR_OBJS := $(patsubst %.c, %.o, $($(CUR_MODULE)-SRC-1)))
	$(eval CUR_OBJS += $(patsubst %.S, %.o, $($(CUR_MODULE)-ASRC-1)))
	ar rcs $@ $(CUR_OBJS)

kernel.bin: $(MEMMAP) $(STARTUP_O) $(MODAS) $(CRT)
	$(ARMGNU)-ld -o kernel.elf -T $^
	$(ARMGNU)-objdump -D kernel.elf > kernel.list
	$(ARMGNU)-objcopy kernel.elf kernel.bin -O binary

# target: help - Display callable targets.
help:
	@egrep "^# target:" [Mm]akefile|sed 's/^# target: //'

.PHONY: config kernel $(CRT) test clean

# target: clean - Clean all targets
clean: clean-test
	rm -f $(AUTOCONF_H)
	rm -f $(ASOBJS) $(OBJS) $(STARTUP_O)
	rm -f $(BCS)
	find . -type f -name "*.bc" -exec rm -f {} \;
	find . -type f -name "*.opt.bc" -exec rm -f {} \;
	find . -type f -name "*.opt.s" -exec rm -f {} \;
	rm -f *.bin
	rm -f *.elf
	rm -f *.list
	rm -f *.a
	$(MAKE) -C $(CRT_DIR) clean
