# Universal unit tests for Zeke project #######################################

# Source code under test
SRCDIR = ../../src/
IDIR = ../../include ../../src ../../src/hal ./config ../../src/dev

include ../punit/Makefile.punit
